version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api
    ports:
      - "8080:8080"
    environment:
      # Basic Configuration
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - CORS_ORIGIN=*
      - DEL_INSTANCE=false
      
      # Authentication (Change this to your own secure key!)
      - AUTHENTICATION_API_KEY=your-secure-api-key-here
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Provider Settings
      - PROVIDER_ENABLED=true
      - PROVIDER_HOST=0.0.0.0
      - PROVIDER_PORT=5656
      - PROVIDER_PREFIX=evolution
      
      # Language
      - LANGUAGE=en
      
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
      - evolution_views:/evolution/views
    restart: unless-stopped
    networks:
      - evolution_network

networks:
  evolution_network:
    driver: bridge

volumes:
  evolution_instances:
  evolution_store:
  evolution_views:
